package src.Threads;

public class GameStates {
    public static final int PRELOAD = 0;
    public static final int LOADING = 1;
    public static final int MAIN_MENU = 10;
    public static final int MAIN_OPTIONS = 11;
    public static final int PAUSE_MENU = 12;
    public static final int OPTIONS_MENU = 15;
    public static final int GAME_OVER = 19;
    public static final int LOAD_MENU = 20;
    public static final int SAVE_MENU = 30;
    public static final int CREDITS = 40;
    public static final int LEVEL_SELECT = 90;
    public static final int LOADING_LEVEL_1 = 91;
    public static final int LOADING_LEVEL_2 = 92;
    public static final int LOADING_LEVEL_3 = 93;
    public static final int LOADING_LEVEL_4 = 94;
    public static final int LOADING_LEVEL_5 = 95;
    public static final int LOADING_LEVEL_6 = 96;
    public static final int LOADING_LEVEL_7 = 97;
    public static final int LOADING_LEVEL_8 = 98;
    public static final int LOADING_LEVEL_9 = 99;
    public static final int RUNNING_NORMAL = 100;
    public static final int PAUSE_NORMAL = 101;
    public static final int PAUSE_NORMAL_OPTIONS = 102;
    public static final int GAMEOVER_NORMAL = 105;
    public static final int GAMEOVER_NORMAL_OPTIONS = 106;
    public static final int RUNNING_ENDLESS = 110;
    public static final int PAUSE_ENDLESS = 111;
    public static final int PAUSE_ENDLESS_OPTIONS = 112;
    public static final int GAMEOVER_ENDLESS = 115;
    public static final int GAMEOVER_ENDLESS_OPTIONS = 116;
    public static final int LOADING_ENDLESS = 119;
    public static final int RUNNING_CLASSIC = 120;
    public static final int PAUSE_CLASSIC = 121;
    public static final int PAUSE_CLASSIC_OPTIONS = 122;
    public static final int GAMEOVER_CLASSIC = 125;
    public static final int GAMEOVER_CLASSIC_OPTIONS = 126;
    public static final int LOADING_CLASSIC = 129;
}
